language: python
python:
  - "3.6"
install:
  - pip install awscli
  - pip install tox
  - pip install -r requirements.txt
script:
# https://github.com/travis-ci/travis-ci/issues/7940
  - export BOTO_CONFIG=/dev/null
  - tox